name: ci
on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ['go124', 'go125', 'go126']
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    name: test (${{ matrix.go }}-${{ matrix.os }})
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/determinate-nix-action@8d87e8d5e5b8a8309d4281094560f127d9a265f1 # v3.22.5
      - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
        with:
          use-flakehub: false
      - run: nix develop .#${{ matrix.go }} --command go mod download
      - run: nix develop .#${{ matrix.go }} --command go build -v
      - run: nix develop .#${{ matrix.go }} --command just test

  test-race:
    strategy:
      fail-fast: false
      matrix:
        go: ['go124', 'go125', 'go126']
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    name: test-race (${{ matrix.go }}-${{ matrix.os }})
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/determinate-nix-action@8d87e8d5e5b8a8309d4281094560f127d9a265f1 # v3.22.5
      - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
        with:
          use-flakehub: false
      - run: nix develop .#${{ matrix.go }} --command just test-race

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/determinate-nix-action@8d87e8d5e5b8a8309d4281094560f127d9a265f1 # v3.22.5
      - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
        with:
          use-flakehub: false
      - run: nix develop .#go126 --command just lint
